In [19]:
# Importing necessary modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

In [20]:
data=pd.read_csv('Code3_Final_29_Variable_Data.csv',index_col = 0)
data.head()

,record,dayssince_fulladdress,vel_fulladdress_30,vel_fulladdress_14,vel_fulladdress_7,vel_fulladdress_3,relv_fulladdress_14,relv_fulladdress_30,relv_fulladdress_60,vel_fulladdress_1,...,dayssince_namessn,vel_namessn_30,vel_namedob_60,vel_ssnnamedob_60,vel_fulladdressphone_14,vel_namessn_60,vel_namedob_14,vel_ssndob_14,vel_ssn_14,fraud_label
0,1,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,2,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,3,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,4,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,5,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [21]:
data.shape

(1000000, 29)

In [22]:
# Z-scale
df2 = (data.iloc[:,1:28] - data.iloc[:,1:28].mean()) / data.iloc[:,1:28].std()
df2.head()

,dayssince_fulladdress,vel_fulladdress_30,vel_fulladdress_14,vel_fulladdress_7,vel_fulladdress_3,relv_fulladdress_14,relv_fulladdress_30,relv_fulladdress_60,vel_fulladdress_1,dayssince_fulladdressphone,...,vel_fulladdressphone_60,dayssince_namessn,vel_namessn_30,vel_namedob_60,vel_ssnnamedob_60,vel_fulladdressphone_14,vel_namessn_60,vel_namedob_14,vel_ssndob_14,vel_ssn_14
0,0.294021,-0.101958,-0.079045,-0.067094,-0.057932,-0.06999,-0.069649,-0.069424,-0.049665,0.278001,...,-0.134077,0.287881,-0.097773,-0.131519,-0.130769,-0.070088,-0.139787,-0.0686,-0.068413,-0.072421
1,0.294021,-0.101958,-0.079045,-0.067094,-0.057932,-0.06999,-0.069649,-0.069424,-0.049665,0.278001,...,-0.134077,0.287881,-0.097773,-0.131519,-0.130769,-0.070088,-0.139787,-0.0686,-0.068413,-0.072421
2,0.294021,-0.101958,-0.079045,-0.067094,-0.057932,-0.06999,-0.069649,-0.069424,-0.049665,0.278001,...,-0.134077,0.287881,-0.097773,-0.131519,-0.130769,-0.070088,-0.139787,-0.0686,-0.068413,-0.072421
3,0.294021,-0.101958,-0.079045,-0.067094,-0.057932,-0.06999,-0.069649,-0.069424,-0.049665,0.278001,...,-0.134077,0.287881,-0.097773,-0.131519,-0.130769,-0.070088,-0.139787,-0.0686,-0.068413,-0.072421
4,0.294021,-0.101958,-0.079045,-0.067094,-0.057932,-0.06999,-0.069649,-0.069424,-0.049665,0.278001,...,-0.134077,0.287881,-0.097773,-0.131519,-0.130769,-0.070088,-0.139787,-0.0686,-0.068413,-0.072421

In [25]:
# Adding record and fraud label
df2['fraud_label'] = data['fraud_label']
df2['record'] = data['record']
cols = list(df2.columns)
cols = [cols[-1]] + cols[:-1]
df2 = df2[cols]
df2.head()

,fraud_label,record,dayssince_fulladdress,vel_fulladdress_30,vel_fulladdress_14,vel_fulladdress_7,vel_fulladdress_3,relv_fulladdress_14,relv_fulladdress_30,relv_fulladdress_60,...,vel_fulladdressphone_60,dayssince_namessn,vel_namessn_30,vel_namedob_60,vel_ssnnamedob_60,vel_fulladdressphone_14,vel_namessn_60,vel_namedob_14,vel_ssndob_14,vel_ssn_14
0,0,1,0.294021,-0.101958,-0.079045,-0.067094,-0.057932,-0.06999,-0.069649,-0.069424,...,-0.134077,0.287881,-0.097773,-0.131519,-0.130769,-0.070088,-0.139787,-0.0686,-0.068413,-0.072421
1,1,2,0.294021,-0.101958,-0.079045,-0.067094,-0.057932,-0.06999,-0.069649,-0.069424,...,-0.134077,0.287881,-0.097773,-0.131519,-0.130769,-0.070088,-0.139787,-0.0686,-0.068413,-0.072421
2,0,3,0.294021,-0.101958,-0.079045,-0.067094,-0.057932,-0.06999,-0.069649,-0.069424,...,-0.134077,0.287881,-0.097773,-0.131519,-0.130769,-0.070088,-0.139787,-0.0686,-0.068413,-0.072421
3,0,4,0.294021,-0.101958,-0.079045,-0.067094,-0.057932,-0.06999,-0.069649,-0.069424,...,-0.134077,0.287881,-0.097773,-0.131519,-0.130769,-0.070088,-0.139787,-0.0686,-0.068413,-0.072421
4,0,5,0.294021,-0.101958,-0.079045,-0.067094,-0.057932,-0.06999,-0.069649,-0.069424,...,-0.134077,0.287881,-0.097773,-0.131519,-0.130769,-0.070088,-0.139787,-0.0686,-0.068413,-0.072421

In [ ]:
pd.to_csv("Code4_Zscaled29.csv")